
#name: "Pull Request Labeler"
#on:
#  - pull_request
#
#jobs:
#  triage:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/labeler@v4.3.0
#        with:
#          configuration-path: ".github/labeler.yml"
#          sync-labels: "true"
#          repo-token: ${{ secrets.SONAR_TOKEN }}

name: "Pull Request Labeler"
on:
  - pull_request

jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@v4.3.0
        with:
          configuration-path: ".github/labeler.yml"
          sync-labels: "true"
          repo-token: ${{ secrets.SONAR_TOKEN }}
